/* Dane przewodnika. Ceny i godziny sprawdzone 06.09.2026; nie są dostępnością na żywo. */
window.GUIDE = {
  verified: '2026-09-06',
  fx: { eur: 4.3179, date: '2026-09-04', peg: 1.95583 },
  hotel: [43.83121, 18.30979],
  sources: {
    hotel: ['Hotel Bosna 1', 'https://www.hotelbosna.ba/'],
    hotelpin: ['Położenie hotelu · OpenStreetMap / Mapcarta', 'https://mapcarta.com/N13789122742'],
    ssst: ['SSST · adres uczelni', 'https://ssst.edu.ba/'],
    ssstpin: ['Położenie SSST · OpenStreetMap / Mapcarta', 'https://mapcarta.com/N7938303252'],
    terminal: ['Terminal Ilidža · OpenStreetMap / Mapcarta', 'https://mapcarta.com/W177028641'],
    vrelo: ['Vrelo Bosne · cennik zarządcy', 'https://zppks.ba/penci-block/vrelo-bosne-cjenovnik/'],
    vrelopin: ['Vrelo Bosne · położenie', 'https://mapcarta.com/18771120'],
    aleja: ['Visit Sarajevo · Velika Aleja', 'https://www.visitsarajevo.ba/listings/velika-aleja-the-great-avenue/'],
    tunnel: ['Tunel Spasa · muzeum, bilety i godziny', 'https://www.mcsarajevo.ba/tunel-spasa'],
    tunnelpin: ['Tunel Spasa · położenie', 'https://mapcarta.com/W119762036'],
    cable: ['Trebevićka žičara · cennik i godziny', 'https://www.zicara.ba/bs/servisne-informacije'],
    cableprice: ['Kolejka · oficjalny cennik z września 2026', 'https://www.zicara.ba/uploads/images/cjenovnik-2026-sep-duo-p_1788507494.png'],
    cablepin: ['Dolna stacja Bistrik · współrzędne', 'https://www.outdooractive.com/en/poi/western-balkans/sarajevo-cable-car-funicular-/42654511/'],
    cityhall: ['Vijećnica · oficjalna strona ratusza', 'https://www.vijecnica.ba/'],
    avaz: ['Avaz · taras widokowy', 'https://avaztwisttower.ba/experiences/observation-deck'],
    avazhours: ['Avaz · informacje partnera biletowego', 'https://culturecard.ba/en/pages/avaz-observation-deck'],
    avazpin: ['Avaz · współrzędne', 'https://en.wikipedia.org/wiki/Avaz_Twist_Tower'],
    yellow: ['Žuta tabija · położenie', 'https://en.wikipedia.org/wiki/%C5%BDuta_Tabija'],
    childhood: ['War Childhood Museum · ceny, adres i godziny', 'https://warchildhood.org/visitor-information/'],
    childhoodpin: ['War Childhood Museum · współrzędne', 'https://dark-tourism.com/index.php/1596-warchildhoodmuseum'],
    bh: ['BH Telecom · oficjalny wykaz placówek', 'https://www.bhtelecom.ba/poslovnice/'],
    bhpin: ['BH Telecom Ilidža · położenie', 'https://fk.maptons.com/p/710444445'],
    petrol: ['Petrol Barska · stacja, godziny i położenie', 'https://www.petrol.ba/prodajna-mjesta/4831-bs-sarajevo-barska-benzinska-stanica'],
    addiko: ['Addiko · oddziały i bankomaty', 'https://www.addiko-fbih.ba/poslovnice-i-bankomati/'],
    bakery: ['Pekara Bentbaša · rejestr działalności', 'https://www.akta.ba/registar/63994/or-pekara-bentbasa-ilidza'],
    bakeryhours: ['Bentbaša · godziny w katalogu, nie na żywo', 'https://restaurantguru.com/Pekara-Bentbasa-Ilidza'],
    ilidzanka: ['Ilidžanka · lokalizacja i informacje w katalogu', 'https://restaurantguru.com/Cevabdzinica-Ilidzanka-Ilidza'],
    ilidzankapin: ['Ilidžanka · adres i kod lokalizacji', 'https://www.top-rated.online/cities/Ilid%C5%BEa/place/p/11899944/%C4%86evabd%C5%BEinica%2BIlid%C5%BEanka'],
    panna: ['Panna Cotta · oficjalna strona', 'https://pannacotta.ba/'],
    pannamenu: ['Panna Cotta · menu', 'https://pannacotta.ba/en-us/menu'],
    pannapin: ['Panna Cotta · położenie w katalogu', 'https://hr.cybo.com/BA-biz/panna-cotta_1O'],
    saray: ['Saray Bosna · adres na stronie lokalu', 'https://www.saraybosna.ba/'],
    saraysocial: ['Saray Bosna · profil lokalu, inny numer adresu', 'https://www.instagram.com/saraybosna_caffe_restoran/'],
    bread: ['Bread&Co Ilidža · adres w katalogu', 'https://stoposto.ba/en/restoran/breadco-ilidza'],
    montana: ['Montana Ilidža · menu dostawy', 'https://www.korpa.ba/partner/montana-ilidza'],
    sokak: ['Sokak Ilidža · menu dostawy', 'https://www.korpa.ba/partner/sokak-ilidza'],
    smash: ['Smash Burger Sa · menu dostawy', 'https://www.korpa.ba/partner/smash-burger-sa'],
    hodzic: ['Hodžić · oficjalne menu i godziny', 'https://hodzic.ba/'],
    burgrs: ['Burgrs · menu dostawy', 'https://korpa.ba/partner/burgrs'],
    beg: ['Ćevabdžinica Beg · adres i oferta', 'https://www.korpa.ba/partner/cevabdzinica-beg'],
    klopa: ['Klopa · oficjalna strona', 'https://restoranklopa.ba/'],
    korpa: ['Korpa · zamówienia pod wskazany adres', 'https://korpa.ba/'],
    gras: ['GRAS · aktualne ceny biletów', 'https://gras.ba/'],
    line3: ['GRAS · tramwaje, w tym linia 3', 'https://gras.ba/tramvajski-saobracaj-8/'],
    tickets: ['GRAS · punkty sprzedaży', 'https://gras.ba/karte/'],
    timetable: ['Rozkłady transportu publicznego kantonu', 'https://www.javniprevozks.ba/account/timetable-public'],
    nbp: ['NBP · tabela A, kurs EUR/PLN', 'https://nbp.pl/statystyka-i-sprawozdawczosc/kursy/tabela-a/'],
    nbpapi: ['NBP · dokumentacja API', 'https://api.nbp.pl/'],
    cbbh: ['Bank centralny BiH · kursy walut', 'https://cbbh.ba/CurrencyExchange/'],
    revolut: ['Revolut · opłaty za wymianę i weekendy', 'https://help.revolut.com/pl-PL/help/wealth/exchanging-money/how-much-does-it-cost-to-make-an-exchange/will-i-be-charged-for-exchanging-foreign-currencies/'],
    revolutfees: ['Revolut Standard · oficjalne opłaty', 'https://www.revolut.com/pl-PL/legal/standard-fees/'],
    card: ['Revolut · płacenie w obcej walucie', 'https://help.revolut.com/pl-PL/help/card-payments-withdrawals/spending-abroad-or-in-different-currencies/tips-for-spending-in-a-foreign-currency/'],
    pko: ['PKO BP · karta za granicą', 'https://www.pkobp.pl/pomoc-kontakt/karty-platnosci/karta-za-granica'],
    pkosettlement: ['PKO BP · rozliczanie transakcji kartą', 'https://www.pkobp.pl/pomoc-kontakt/karty-platnosci/jak-rozliczane-sa-transakcje-wykonane-karta'],
    sunday: ['Federacja BiH · ustawa o handlu, art. 18', 'https://fbihvlada.gov.ba/bs/21-zakon-o-unutrasnjoj-trgovini'],
    emergency: ['FCDO · lokalne numery alarmowe', 'https://www.gov.uk/foreign-travel-advice/bosnia-and-herzegovina/getting-help'],
    safety: ['FCDO · bezpieczeństwo w BiH', 'https://www.gov.uk/foreign-travel-advice/bosnia-and-herzegovina/safety-and-security'],
    airalo: ['Airalo · pomoc i instrukcje eSIM', 'https://www.airalo.com/help/'],
    airport: ['Port lotniczy Sarajewo', 'https://www.sarajevo-airport.ba/'],
    lot: ['LOT · informacje o podróży', 'https://www.lot.com/pl/pl/podrozuj'],
    mostar: ['UNESCO · Stary Most i historyczne centrum Mostaru', 'https://whc.unesco.org/en/list/946/'],
    rail: ['Koleje Federacji BiH · sprawdź rozkład przed wyjazdem', 'https://www.zfbh.ba/'],
    osm: ['OpenStreetMap · autorzy mapy', 'https://www.openstreetmap.org/copyright']
  },
  places: [
    {id:'hotel',name:'Hotel Bosna 1',cat:'base',area:'Ilidža',address:'Butmirska cesta 8',pos:[43.83121,18.30979],desc:'Punkt startowy wszystkich odległości i przycisków „Z hotelu”. Recepcja pomoże zamówić samochód i potwierdzić wymeldowanie.',hours:'Godzinę wymeldowania potwierdź w recepcji.',phone:'+38733771340',sources:['hotel','hotelpin']},
    {id:'ssst',name:'SSST · szkoła letnia',cat:'base',area:'Ilidža',address:'Hrasnička cesta 3a',pos:[43.82388,18.30851],desc:'Zajęcia eXcape od poniedziałku do środy. W poniedziałek rejestracja w Innovation Lab; we wtorek rotacje w salach 315 i 318.',hours:'Start programu 09:30; szczegóły w zakładce Plan.',sources:['ssst','ssstpin']},
    {id:'terminal',name:'Terminal Ilidža',cat:'travel',area:'Ilidža',address:'Kompleks przesiadkowy Ilidža',pos:[43.83097,18.30842],desc:'Okolica pętli tramwajowej i dworca autobusowego. Do Starego Miasta szukaj tramwaju linii 3 w kierunku Baščaršija. Punkt na mapie oznacza kompleks, nie konkretny peron.',hours:'Aktualny rozkład sprawdź u operatora. Kup i skasuj właściwy bilet.',price:2.2,unit:'bilet jednorazowy od',sources:['terminal','line3','gras','tickets']},
    {id:'vrelo',name:'Vrelo Bosne',cat:'see',area:'Ilidža',address:'Park źródeł rzeki Bosny',pos:[43.81774,18.26975],desc:'Zielony spacer wśród źródeł, wody i mostków. Dobry wybór na spokojny czwartek. Pin wskazuje rejon źródeł; wejście do parku sprawdź w nawigacji.',hours:'Zaplanuj wizytę za dnia. Nie potwierdzono aktualnych godzin bram.',price:6,unit:'zagraniczny dorosły',time:'Zarezerwuj 1,5–2 h w parku',sources:['vrelo','vrelopin']},
    {id:'aleja',name:'Velika Aleja',cat:'see',area:'Ilidža',address:'Aleja prowadząca w stronę Vrelo Bosne',desc:'Około 3,5 km zielonej alei. Można przejść tylko jej fragment po zajęciach albo połączyć ją z parkiem w czwartek. Sam spacer aleją nie zastępuje biletu do Vrelo Bosne.',hours:'Najlepiej w świetle dziennym.',price:0,unit:'spacer aleją',time:'Krótki wariant: 45–90 min',sources:['aleja']},
    {id:'tunnel',name:'Tunel Ocalenia',cat:'see',area:'Ilidža',address:'Tuneli 1, Donji Kotorac',pos:[43.81982,18.33735],desc:'Muzeum tunelu pod pasem lotniska, który pomagał łączyć oblężone Sarajewo ze światem. Autentyczny fragment, odtworzony odcinek i ekspozycja historyczna.',hours:'Kwiecień–październik 08:30–17:00; ostatnie wejście 16:30.',price:20,student:8,unit:'normalny',notice:'Tylko gotówka w KM. Muzeum nie przyjmuje kart ani obcych walut. Zabierz legitymację do ulgi.',time:'Zarezerwuj 60–90 min',phone:'+38733778670',sources:['tunnel','tunnelpin']},
    {id:'cable',name:'Kolejka na Trebević',cat:'see',area:'Centrum',address:'Dolna stacja Bistrik, Hrvatin bb',pos:[43.855467,18.435103],desc:'Wjazd ponad miasto i spacer przy górnej stacji. Po zajęciach wybierz widoki, nie długą wyprawę na szczyt. Przy złej pogodzie lub późnym wyjściu przełóż na czwartek.',hours:'Pon. 12:00–19:00; wt.–niedz. 09:00–19:00. Przed wyjściem sprawdź komunikaty operatora.',price:30,unit:'w obie strony',notice:'Jeden kierunek 20 KM. Pakiet kolejka + Vijećnica 35 KM. Stawki turystyczne, nie ulgowe ceny dla mieszkańców.',time:'Po zajęciach celuj w dolną stację do ok. 17:30',phone:'+38733246573',sources:['cable','cableprice','cablepin']},
    {id:'cityhall',name:'Vijećnica · ratusz',cat:'see',area:'Centrum',address:'Obala Kulina bana, Sarajevo',desc:'Wnętrze zabytkowego ratusza jako dodatek do kolejki lub wariant na deszcz. Samodzielnego biletu i godzin nie potwierdzono tutaj; sprawdź oficjalną stronę.',price:35,unit:'pakiet z kolejką',notice:'35 KM obejmuje pakiet, a nie sam wstęp do ratusza. Nie dodawaj do tego ponownie 30 KM za kolejkę.',sources:['cityhall','cableprice']},
    {id:'avaz',name:'Avaz Twist Tower',cat:'see',area:'Centrum',address:'Tešanjska 24a',pos:[43.86075,18.402111],desc:'Taras widokowy w zachodniej części centrum. Opcja na panoramę miasta bez całej górskiej wycieczki.',hours:'Partner biletowy podaje 07:00–23:00. Późny wstęp potwierdź przed dojazdem.',price:5,unit:'taras widokowy',time:'Zarezerwuj 45–60 min',sources:['avaz','avazhours','avazpin']},
    {id:'yellow',name:'Žuta tabija · Żółta Twierdza',cat:'see',area:'Centrum',address:'Jekovac, ponad Starym Miastem',pos:[43.86148,18.437741],desc:'Dodatkowy punkt widokowy nad dachami Sarajewa. Dobry cel na krótki spacer pod górę po zwiedzaniu centrum. Powrót zaplanuj po oświetlonej trasie.',hours:'Wybierz pogodny wieczór i sprawdź dostęp na miejscu.',time:'Zarezerwuj 45–75 min ze spacerem',sources:['yellow']},
    {id:'childhood',name:'War Childhood Museum',cat:'see',area:'Centrum',address:'Logavina 32',pos:[43.8619,18.4284],desc:'Muzeum dzieciństwa w czasie wojny: osobiste historie i przedmioty, a nie kolejna panorama. Dobry wariant na deszcz; temat może być emocjonalnie trudny.',hours:'Codziennie 11:00–19:00; ostatnie wejście 18:30.',price:15,student:12,unit:'normalny',notice:'Muzeum przyjmuje karty. Weź legitymację do biletu studenckiego.',time:'Zarezerwuj 60–90 min',sources:['childhood','childhoodpin']},
    {id:'ilidzanka',name:'Ćevabdžinica Ilidžanka',cat:'food',area:'Ilidža',address:'Harisa Merzića · kod mapy R8J5+968',pos:[43.8309125,18.308078125],desc:'Lokal na ćevapi blisko bazy. Nie udało się potwierdzić aktualnego menu z cenami, dlatego wcześniejszych „44 zł za dwie osoby” nie traktuj jako oferty.',hours:'Godziny i płatność sprawdź na miejscu.',notice:'Katalog wskazuje gotówkę. Numeru budynku 21 z wcześniejszej rozmowy nie potwierdzono.',phone:'+38733625103',sources:['ilidzanka','ilidzankapin']},
    {id:'sokak',name:'Sokak Ilidža',cat:'food',area:'Ilidža',address:'Dr. Mustafe Pintola 25 · Hotel Hollywood',desc:'Konkretny tani wariant z menu dostawy: duży döner z kurczakiem 10 KM. Dwa takie döner kebaby kosztują 20 KM przed opłatą za dostawę i napojami.',price:10,unit:'duży döner z kurczakiem',pair:20,pairlabel:'2 duże döner kebaby',hours:'Aktualną dostępność pod adres hotelu pokazuje Korpa.',notice:'Cennik dostawy może różnić się od ceny na miejscu.',phone:'+38733943202',sources:['sokak']},
    {id:'montana',name:'Montana Ilidža',cat:'food',area:'Ilidža',address:'Mala Aleja 65',desc:'Pizza zamiast grilla. W menu dostawy Margarita 9,50 KM, Bosanska 12,90 KM. Dwie Margarity: 19 KM; dwie Bosanskie: 25,80 KM.',price:9.5,unit:'pizza Margarita',pair:19,pairlabel:'2 pizze Margarita',hours:'Sprawdź dostępność w menu online.',notice:'Bez napojów i opłat dostawy. Ceny na miejscu mogą być inne.',sources:['montana']},
    {id:'panna',name:'Panna Cotta',cat:'food',area:'Ilidža',address:'Mala Aleja bb',pos:[43.8304375,18.306359375],desc:'Kawa, deser lub spokojna przerwa w Ilidžy. Link prowadzi do menu lokalu; nie podajemy cen, których nie udało się odczytać i potwierdzić.',hours:'Godziny sprawdź bezpośrednio w lokalu.',phone:'+38733629380',sources:['panna','pannamenu','pannapin']},
    {id:'saray',name:'Saray Bosna',cat:'food',area:'Ilidža',address:'Butmirska cesta · numer do potwierdzenia',desc:'Lokal wspomniany w rozmowie. Oficjalna witryna podaje numer 21, profil społecznościowy numer 15. Otwórz wyszukiwanie lokalu w Mapach zamiast kierować się niepewnym numerem.',notice:'Rozbieżny adres; brak potwierdzonego cennika. Nie jest przypięty precyzyjną gwiazdką.',sources:['saray','saraysocial']},
    {id:'bread',name:'Bread&Co Ilidža',cat:'food',area:'Ilidža',address:'Dobrinjska 3',desc:'Alternatywa w okolicy. Wcześniej wskazana Mala Aleja 61 nie została potwierdzona; katalog restauracji podaje Dobrinjska 3.',notice:'Przed dojściem sprawdź adres, godziny i menu w Mapach lub lokalu.',sources:['bread']},
    {id:'hodzic',name:'Ćevabdžinica Hodžić',cat:'food',area:'Centrum',address:'Bravadžiluk 34',desc:'Ćevapi na Starym Mieście, nie przy hotelu. Menu lokalu: 5 sztuk 7 KM, 10 sztuk 14 KM, 15 sztuk 21 KM. Kajmak 2,50 KM, woda 3 KM.',hours:'Oficjalna strona podaje codziennie 07:00–23:00.',price:14,unit:'10 ćevapi',pair:28,pairlabel:'2 porcje po 10 ćevapi',notice:'Dwie porcje + dwa kajmaki + dwie wody: 39 KM. Akceptacji kart nie potwierdzono.',phone:'+38733532866',sources:['hodzic']},
    {id:'smash',name:'Smash Burger Sa',cat:'food',area:'Centrum',address:'Sarači 64',desc:'W menu dostawy klasyczny burger 13 KM. Zestaw z frytkami i napojem 19,50 KM w pokazanej promocji; cena regularna zestawu 21 KM.',price:13,unit:'klasyczny burger',pair:39,pairlabel:'2 zestawy w pokazanej promocji',notice:'Cena promocji i dostępność mogą się zmienić; bez opłaty dostawy.',phone:'+38762228850',sources:['smash']},
    {id:'burgrs',name:'Burgrs',cat:'food',area:'Poza Ilidžą',address:'Džemala Bijedića 42B',desc:'Burgerownia w innej części miasta. Nie jest opcją „obok hotelu”. Aktualne ceny sprawdź w podlinkowanym menu.',phone:'+38733743549',sources:['burgrs']},
    {id:'beg',name:'Ćevabdžinica Beg',cat:'food',area:'Centrum',address:'Mudželiti Veliki 12',desc:'Kolejna opcja na ćevapi podczas spaceru po centrum. Wcześniejsza ogólna cena z rozmowy nie była zweryfikowanym cennikiem.',sources:['beg']},
    {id:'klopa',name:'Klopa',cat:'food',area:'Centrum',address:'Trg fra Grge Martića 4',desc:'Restauracja przy placu katedralnym. Ceny pizzy i risotta podane wcześniej w rozmowie nie zostały tu potwierdzone; sprawdź menu lokalu.',phone:'+38733223633',sources:['klopa']},
    {id:'bakery',name:'Pekara Bentbaša',cat:'shop',area:'Ilidža',address:'Butmirska cesta 5',desc:'Piekarnia w okolicy hotelu. Opcja na pieczywo i szybkie jedzenie, również do sprawdzenia w niedzielę.',hours:'Katalog podaje 06:00–18:00 codziennie. To informacja wtórna, nie potwierdzenie otwarcia teraz.',notice:'Aktualnych cen i akceptacji kart nie potwierdzono.',sources:['bakery','bakeryhours']},
    {id:'petrol',name:'Petrol · Barska',cat:'shop',area:'Ilidža',address:'Barska 0N / bb',pos:[43.836384,18.299416],desc:'Stacja ze sklepem, kawą i bankomatem. Praktyczna możliwość na drobne zakupy w niedzielę. Nie jest tuż za drzwiami hotelu i nie została potwierdzona jako najbliższa stacja.',hours:'Oficjalnie codziennie 06:00–23:00.',phone:'+38733762275',sources:['petrol']},
    {id:'atm',name:'Addiko ATM · Grand Centar',cat:'shop',area:'Ilidža',address:'Butmirska cesta 14',desc:'Bankomat w Grand Centar. Sprawdź dostęp do urządzenia i opłatę na jego ekranie, zanim zatwierdzisz wypłatę.',notice:'Wypłata w BAM bez DCC nie oznacza wypłaty bez prowizji. Nie potwierdzono dostępu całodobowego ani opłaty dla Twojej karty.',sources:['addiko']},
    {id:'sim',name:'BH Telecom · Ilidža',cat:'shop',area:'Ilidža',address:'Mala Aleja 44',pos:[43.8295539,18.3072239],desc:'Oficjalny punkt na lokalną kartę prepaid / tourist SIM. Zapytaj o ilość danych, ważność i uruchomienie na miejscu. Cen pakietów nie zgadujemy.',hours:'Pon.–pt. 09:00–17:00; sob. 09:00–14:00; niedz. zamknięte.',notice:'Weź dokument tożsamości. W dni zajęć placówka może zamknąć się przed Twoim powrotem.',phone:'+38733620070',sources:['bh','bhpin']},
    {id:'airport',name:'Lotnisko Sarajewo · SJJ',cat:'travel',area:'Ilidža',address:'Kurta Schorka 36 · terminal odlotów',desc:'W piątek powrót LOT LO578 o 13:05. Cel planu: być w terminalu około 11:00. Godzinę lotu i bramkę potwierdź w aplikacji LOT.',hours:'Planowany odbiór samochodem z hotelu 10:20–10:30, do uzgodnienia z recepcją.',notice:'Nie idź na skróty w stronę pasa startowego. Nawiguj do terminalu pasażerskiego.',sources:['airport','lot']},
    {id:'mostar',name:'Mostar · alternatywa na cały dzień',cat:'see',area:'Dalej',address:'Stari Most, Mostar',desc:'Stary Most i historyczne centrum to opcja zamiast lokalnego czwartku, nie dodatek do niego. Wymaga osobnego sprawdzenia połączeń i powrotu. Tego wyjazdu nie rezerwowano.',hours:'Bez potwierdzonego rozkładu, ceny i czasu przejazdu w tym przewodniku.',notice:'Przed decyzją sprawdź połączenie w obie strony. Na piątek z lotem o 13:05 tej wycieczki nie planuj.',sources:['mostar','rail']}
  ],
  days: [
    {id:'sun',date:'2026-09-06',short:'Niedz.',number:'06',title:'Lądowanie. Spokojny start.',subtitle:'Dzisiaj bez gonienia atrakcji. Jedzenie, orientacja w Ilidžy i sprawny internet.',events:[
      {time:'Po przylocie',title:'Hotel i krótki reset',text:'Zostaw rzeczy, zapisz hotel w Mapach, potwierdź śniadanie i wymeldowanie. Nie planuj kolejnego dalekiego dojazdu.',place:'hotel',kind:'own'},
      {time:'Popołudnie',title:'Zjedzcie coś blisko',text:'Dwa duże döner kebaby w Sokak: 20 KM według menu dostawy. Alternatywnie dwie Margarity w Montana: 19 KM. Napoje i dowóz osobno.',place:'sokak',kind:'own'},
      {time:'Bez pośpiechu',title:'Pętla, gotówka, eSIM',text:'Zobaczcie okolice terminalu Ilidža. Upewnij się, że internet działa bez Wi-Fi. Na niedzielne zakupy sprawdź piekarnię lub Petrol, nie zakładaj otwarcia supermarketu.',place:'terminal',kind:'own'}]},
    {id:'mon',date:'2026-09-07',short:'Pon.',number:'07',title:'eXcape i Stare Miasto.',subtitle:'Dzień z organizatorami. Nie dokładamy równoległego planu zwiedzania.',events:[
      {time:'08:50',title:'Wyjście w stronę SSST',text:'To nasz proponowany zapas, nie godzina zbiórki. Trasę sprawdź w Mapach; przed 09:30 znajdź Innovation Lab.',place:'ssst',kind:'own'},
      {time:'09:30–10:00',title:'Rejestracja i kawa',text:'Innovation Lab. Pierwszy punkt agendy szkoły letniej.',place:'ssst',kind:'agenda'},
      {time:'10:00–10:45',title:'Powitanie i wprowadzenie',text:'10:00–10:15 welcome address; 10:15–10:45 wprowadzenie do Summer School.',kind:'agenda'},
      {time:'10:45–13:00',title:'Prezentacje zespołów i Challenge',text:'Agenda umieszcza w porannym bloku prezentacje krajów oraz zadanie Challenge. Dokładnego podziału na podbloki nie podaje.',kind:'agenda'},
      {time:'13:00–14:00',title:'Brak opisu w agendzie',text:'Nie dopisujemy tu własnej aktywności. Ustal z organizatorami, czy to przerwa, czy dalsza część programu.',kind:'check'},
      {time:'14:00–15:30',title:'Lunch',text:'Zgodnie z przesłanym planem.',kind:'agenda'},
      {time:'16:00',title:'Zwiedzanie Starego Miasta',text:'Tour of Old Town Sarajevo z grupą. Miejsce zbiórki i transfer ustal z prowadzącymi.',kind:'agenda'}]},
    {id:'tue',date:'2026-09-08',short:'Wt.',number:'08',title:'VR, zespoły i luźny wieczór.',subtitle:'Po zajęciach zostaw miejsce na zaproszenie od grupy. Spacer jest tylko opcją.',events:[
      {time:'09:30–10:15',title:'Wprowadzenie do VR i podział na zespoły',text:'09:30 wprowadzenie i przegląd projektu, od 10:00 wybór zespołów; w planie również Beat Saber.',place:'ssst',kind:'agenda'},
      {time:'Blok poranny',title:'Testy eXcape / Beat Saber',text:'Zespoły 1 i 2 testują eXcape w sali 315. Zespoły 3 i 4 grają w Beat Saber w sali 318. Agenda nie pozwala pewnie odczytać wszystkich godzin rotacji.',kind:'agenda'},
      {time:'13:00–14:00',title:'Lunch',text:'Przerwa obiadowa z agendy.',kind:'agenda'},
      {time:'Po lunchu',title:'Zamiana aktywności zespołów',text:'Zespoły 1 i 2: Beat Saber. Zespoły 3 i 4: testy eXcape. Godzina końca zajęć nie jest wyraźnie określona.',kind:'agenda'},
      {time:'Po zajęciach',title:'Velika Aleja albo kawa',text:'Przy wyjściu około 16:00 wybierzcie 45–90 min spokojnego spaceru, a potem kolację w Ilidžy. Gdy grupa ma swój plan, tę propozycję po prostu pomińcie.',place:'aleja',kind:'option'}]},
    {id:'wed',date:'2026-09-09',short:'Śr.',number:'09',title:'Finał szkoły. Potem widoki.',subtitle:'Kolejka tylko przy dobrej pogodzie i sprawnym dojeździe. Bez wyścigu z zamknięciem.',events:[
      {time:'Od 09:30',title:'Dyskusja, feedback i końcowe testy',text:'Poranny blok dnia trzeciego według agendy.',place:'ssst',kind:'agenda'},
      {time:'13:00–14:00',title:'Podsumowanie i zakończenie',text:'Closing remarks.',kind:'agenda'},
      {time:'14:00–15:30',title:'Lunch',text:'Zgodnie z agendą.',kind:'agenda'},
      {time:'16:00',title:'Czas wolny',text:'Free activities. Najpierw sprawdź plan grupy i aktualny komunikat kolejki.',kind:'agenda'},
      {time:'16:00–17:30',title:'Opcja: dojazd do dolnej stacji',text:'Z Ilidžy zarezerwuj orientacyjnie 60–75 min na tramwaj i dojście; to bufor planu, nie pomiar na żywo. Cel: stacja Bistrik najpóźniej około 17:30.',place:'cable',kind:'option'},
      {time:'Do ok. 18:30',title:'Widoki i zjazd z zapasem',text:'Kolejka działa do 19:00 według rozkładu. Potwierdź ostatni zjazd w kasie. Bez długiego szlaku; gdy jest późno lub pogoda słaba, przełóż na czwartek.',place:'cable',kind:'option'},
      {time:'Wieczór',title:'Kolacja w centrum lub z grupą',text:'Hodžić: dwie porcje po 10 ćevapi to 28 KM, bez dodatków i napojów. Nie jedź specjalnie do centrum wyłącznie dla tej ceny.',place:'hodzic',kind:'option'}]},
    {id:'thu',date:'2026-09-10',short:'Czw.',number:'10',title:'Jeden wolny dzień. Dwie dobre rzeczy.',subtitle:'Wariant podstawowy po stronie Ilidžy: natura rano, historia po południu. Godziny poniżej to propozycja.',events:[
      {time:'09:00',title:'Śniadanie i Velika Aleja',text:'Wybierz spacer do Vrelo Bosne albo podjazd, jeżeli nie macie ochoty na dłuższe chodzenie. Zabierz wodę, gotówkę i legitymację.',place:'aleja',kind:'own'},
      {time:'10:00–11:30',title:'Vrelo Bosne',text:'Źródła, mostki i spokojna przerwa. Bilety dla dwóch zagranicznych dorosłych: 12 KM. Czas dojścia zależy od wybranej trasy.',place:'vrelo',kind:'own'},
      {time:'12:30',title:'Lunch w Ilidžy',text:'Zaplanowany budżet i wybrane menu sprawdzisz w Portfelu. Nie wliczamy automatycznie opłat dostawy.',place:'montana',kind:'own'},
      {time:'13:30',title:'Przejazd do Tunelu Ocalenia',text:'Samochód zamów przez recepcję lub uzgodnij cenę / taksometr przed kursem. Zarezerwuj zapas zamiast polegać na wcześniejszych „6 minutach”.',place:'tunnel',kind:'own'},
      {time:'14:00–15:15',title:'Tunel Ocalenia',text:'Normalny 20 KM, studencki 8 KM od osoby. Płatność wyłącznie gotówką w KM. W planie jesteśmy przed ostatnim wejściem o 16:30.',place:'tunnel',kind:'own'},
      {time:'Od 16:00',title:'Reszta dnia bez rezerwacji',text:'Kawa i pakowanie albo centrum, jeśli macie energię. Jeśli kolejka wypadła ze środy, przebudujcie czwartek zamiast upychać wszystkie atrakcje.',place:'panna',kind:'option'}]},
    {id:'fri',date:'2026-09-11',short:'Pt.',number:'11',title:'Powrót bez sprintu.',subtitle:'Godziny lotu potwierdzone w wiadomości LOT. Transfer jest propozycją, nie dokonaną rezerwacją.',events:[
      {time:'Rano',title:'Śniadanie, pakowanie, wymeldowanie',text:'Sprawdź dokument, kartę pokładową, telefon i ładowarkę. Godzinę wymeldowania ustal z recepcją.',place:'hotel',kind:'own'},
      {time:'10:20–10:30',title:'Proponowany odbiór z hotelu',text:'Zamów samochód wcześniej; nie ma tu rezerwacji ani gwarantowanego czasu przejazdu. Ustal kurs do terminalu pasażerskiego SJJ.',place:'airport',kind:'own'},
      {time:'Około 11:00',title:'Cel: być już na lotnisku',text:'To nasz bezpieczny zapas w planie. Aktualne wymagania odprawy, boarding i bramkę sprawdź w LOT.',place:'airport',kind:'own'},
      {time:'13:05 → 14:50',title:'LO578 · Sarajewo → Warszawa',text:'Piątek 11 września 2026. Planowy wylot SJJ 13:05, przylot WAW 14:50. Potwierdzenie rezerwacji w mailu; sprawdź ewentualne zmiany w aplikacji.',kind:'flight'}]}
  ]
};
